### ISSUE TITLE
update biobb_model requirements in the conda recipe

### ISSUE THREAD

**Issue by pgbarletta** [bioexcel/biobb_structure_utils#11]
Hi,
I think the conda requirements are outdated. This is what I got when I tried to install this package following the docs:

```
Downgrade:
──────────────────────────────────────────────────────────────────────────────────────

  - biobb_model                 3.7.0  pyhdfd78af_0  installed                      
  + biobb_model                 0.1.6  py_1          bioconda/noarch          Cached

```

I ended up installing using pip, which doesn't have a `biobb_model` requirement, though I did get the following error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
biobb-model 3.7.0 requires biobb-structure-checking==3.8.5, but you have biobb-structure-checking 3.9.11 which is incompatible.
```

**Comment by gbayarri** [comment]
Hi, 

Try to install it via environment file. First off, create an environment.yaml file:

```
name: my_conda_env_name
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_model==3.7.0
  - conda
```

`conda env create --file environment.yaml`

If you need modeller and you have a license, you must install it in this new environment:

```
conda activate my_conda_env_name
conda install -c salilab modeller
```

There's two ways of registering the Modeller Key:

* Through the config.py file:
  * Edit: PATH_TO_CONDA_ENV]/lib/modeller-10.1/modlib/modeller/config.py
  * Add line: license = r'MY_MODELLER_KEY'
* Through the env variable KEY_MODELLER:
  * Edit: [PATH_TO_CONDA_ENV]/lib/modeller-10.1/modlib/modeller/config.py
  * Comment line: license = r'MY_MODELLER_KEY'
  * Set the KEY_MODELLER env var: export KEY_MODELLER="MY_MODELLER_KEY"

Please let me know if it worked.

**Comment by pgbarletta** [comment]
right, but if I do that, then I have to install this package (`biobb_structure_utils`) and I'd be back to where I started. And if I add this package as a requirement as well:
```
name: my_conda_env_name
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_model==3.7.0
  - biobb_structure_utils>=3.7.6
  - conda
```
Then conda complains about the incompatibility:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package ncurses conflicts for:
conda -> python[version='>=3.8,<3.9.0a0'] -> ncurses[version='5.9.*|5.9|>=6.1,<7.0.0a0|>=6.2,<7.0.0a0|>=6.3,<7.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.0,<7.0a0|6.0.*']
biobb_model==3.7.0 -> python=3.7 -> ncurses[version='>=6.1,<7.0.0a0|>=6.2,<7.0.0a0|>=6.3,<7.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
biobb_structure_utils[version='>=3.7.6'] -> python=3.7 -> ncurses[version='>=6.1,<7.0.0a0|>=6.2,<7.0.0a0|>=6.3,<7.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']

Package setuptools conflicts for:
biobb_structure_utils[version='>=3.7.6'] -> biobb_structure_checking==3.9.11 -> setuptools
conda -> ruamel_yaml -> setuptools
conda -> setuptools[version='>=31.0.1']

Package biobb_structure_checking conflicts for:
biobb_model==3.7.0 -> biobb_structure_checking==3.8.5
biobb_structure_utils[version='>=3.7.6'] -> biobb_structure_checking==3.9.11
```

I don't see a way around without updating the conda recipe.

**Comment by gbayarri** [comment]
Hi,

Unless you really need the last version of the biobb_structure_utils, I recommend you to try with biobb_structure_utils 3.7.1.

Here you can find an environment.yaml with all the 3.7.0 / 3.7.1 BioBB's:

https://github.com/bioexcel/utils_biobb/blob/master/utils_biobb/environment_files/environment-3.7.yml

We have this environment up and running in several workers with no dependencies problems.

We will release shortly the new 3.8 version of the BioBB's, so all these problems should disappear.

Best.

**Comment by pgbarletta** [comment]
great, 3.7.1 does it.
Thanks!
