### ISSUE TITLE
Extract_molecule calls cmd_wrapper

### ISSUE THREAD

**Issue by PauAndrio** [bioexcel/biobb_structure_utils#13]
extract_molecule calls cmd_wrapper instead of creating self.cmd  https://github.com/bioexcel/biobb_structure_utils/blob/91617c5562b9235d7900488054dd8f7dbb636ac7/biobb_structure_utils/utils/extract_molecule.py#L115

**Comment by gbayarri** [comment]
Done, will be available in next release
